{{- range .Values.clusters }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .destinationName }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: {{ .destinationName }}
  server: {{ .server }}
  project: {{ .project }}
{{- end }}
